echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo " $IS_SELECTEDQ Q) Filters car crop off date between January to October of 2023 in ascending order by month."
echo " $IS_SELECTEDW W) List company names in ascending order."
echo " $IS_SELECTEDE E) Filters Coverage ID's with no accidental damage and exterior coverage option (exluding coverage ID #6.."
echo " $IS_SELECTEDR R) Ranks by brake type."
echo " $IS_SELECTEDT T) Creates a list of unique pickup locations and total number of pickups that occured at that location."
echo " $IS_SELECTEDY Y) Displays customer details in ascending order of country & surnames in descending order."
echo " $IS_SELECTEDU U) Calculates the total value of each promotion and displays the total values for each promotion in descending order."
echo " $IS_SELECTEDI I) Ranks by monthly price."
echo " $IS_SELECTEDO O) Displays storage option: yes, dollyoption: no, movingboxes: no."
echo " $IS_SELECTEDP P) Shows emails corresponding from the @gmail domain."
echo " $IS_SELECTEDA A) Sums tax and total and shows the new total."
echo " $IS_SELECTEDS S) Tells when the drop off location is greater than, equal to, or less than 4321."
echo " $IS_SELECTEDD D) Changes titles of columns and removes the no options from storage option."
echo " $IS_SELECTEDF F) Selects specific reservations where the rented car has a total mileage greater than 50000km and an engine size of 2.4L."
echo " $IS_SELECTEDG G) Selects specific customers where the car has a description 'Gas', 'All-Wheel', 'Auto', and a rental price greater or equal to 200> "
echo " $IS_SELECTEDH H) Selects specific reservations where the rented car has more than or equal to 4 seats, and is of fuel type '87 Octane'."
echo " $IS_SELECTEDJ J) Shows monthly price."
echo " $IS_SELECTEDK K) Orders rental price by card types."
echo " $IS_SELECTEDL L) Shows average rental prices greater than 100 by Card Types."
echo " $IS_SELECTEDB B) Shows monthly prices that are greater than the average monthly price."
echo " $IS_SELECTEDN N) Shows the number of unique birth years between 1960 and 2004."
echo " $IS_SELECTEDM M) Counts the number of low, mid, and high spenders in DB."  
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
